backend:
  name: git-gateway
  branch: main
  local_backend: true

media_folder: "src/uploads"
public_folder: "/uploads"

collections:
  # 1. KOLEKSI ARTIKEL
  - name: "posts"
    label: "Articles"
    folder: "src/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - {
          label: "Layout",
          name: "layout",
          widget: "hidden",
          default: "layouts/post.njk",
        }
      # Tags diganti jadi 'list' biar bisa input banyak
      - { label: "Tags", name: "tags", widget: "list", default: ["posts"] }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - {
          label: "Author",
          name: "author",
          widget: "string",
          default: "RIZKY HAMMER",
        }
      - {
          label: "Category",
          name: "category",
          widget: "select",
          options: ["MUSIC", "FILM", "VISUAL", "EVENTS"],
        }
      - { label: "Cover Image", name: "image", widget: "image" }
      - { label: "Excerpt (Intro)", name: "excerpt", widget: "text" }
      - { label: "Body Content", name: "body", widget: "markdown" }

  # 2. KOLEKSI PENGATURAN (Baru)
  # 2. KOLEKSI PENGATURAN (Baru)
  - name: "settings"
    label: "Site Settings"
    delete: false
    editor:
      preview: false
    files:
      - name: "global"
        label: "Global Settings (Hero & Marquee)"
        file: "src/_data/global.json"
        fields: # <--- Cukup satu aja fields-nya, langsung list di bawah
          - { label: "Site Name / Logo", name: "site_title", widget: "string" }
          - {
              label: "Hero Text 1 (Solid - Kiri Atas)",
              name: "hero_text_solid",
              widget: "string",
            }
          - {
              label: "Hero Text 2 (Outline - Kanan Bawah)",
              name: "hero_text_outline",
              widget: "string",
            }
          - { label: "Hero Sub-text", name: "hero_sub", widget: "string" }

          # --- TAMBAHAN MANIFESTO ---
          - {
              label: "Manifesto Title",
              name: "manifesto_title",
              widget: "string",
            }
          - { label: "Manifesto Body", name: "manifesto_text", widget: "text" }
          - {
              label: "Manifesto Button",
              name: "manifesto_btn",
              widget: "string",
            }
          # --------------------------

          - { label: "Top Marquee Text", name: "marquee_top", widget: "string" }
          - {
              label: "Bottom Marquee Text",
              name: "marquee_bottom",
              widget: "string",
            }
